// Deterministic initial headers: no browser, network or page API required.
// Run with --check in CI, or without it after changing shared header data.
import fs from 'node:fs/promises';
import path from 'node:path';
import crypto from 'node:crypto';
import {labels,destinations,featured,groups,descriptions,socials,resources,pageSections} from './header-data.mjs';
const site = path.resolve(import.meta.dirname,'../site');
const marker = /<!-- BULLEN_SHELL_START[\s\S]*?<!-- BULLEN_SHELL_END -->/;
const check = process.argv.includes('--check');
const hash = crypto.createHash('sha256').update(await fs.readFile(new URL('./header-data.mjs',import.meta.url))).update(await fs.readFile(import.meta.filename)).digest('hex');
const escape = s => String(s).replace(/&/g,'&amp;').replace(/</g,'&lt;').replace(/"/g,'&quot;');
const chevron = '<span class="bullen-header-chevron" aria-hidden="true"></span>';
const external = ' target="_blank" rel="noopener noreferrer"';
const extraLink = ([href,label]) => `<a href="${escape(href)}"${external}>${escape(label)}<span aria-hidden="true">↗</span></a>`;
const shell = (name,source) => {
 const page=name.replace(/\.html$/,''),active=page.startsWith('patchnotes-')?'patchnotes':page;
 const label=labels[active]||'The House';
 const sections=(pageSections[page]||[]).filter(([id])=>source.includes(`id="${id}"`));
 const current=key=>key===active?' aria-current="page"':'';
 const navLink=key=>`<a class="bullen-header-destination bullen-header-${key}" href="${destinations[key]}"${current(key)}>${escape(labels[key]).toUpperCase()}</a>`;
 const groupsHtml=groups.map(([group,keys],index)=>`<details class="bullen-header-group"${index===0?' open':''}><summary>${escape(group)}${chevron}</summary><div class="bullen-header-group-links">${keys.map(key=>`<a href="${destinations[key]}"${current(key)}${key==='bullensaga'||key==='whitepaper'?external:''}><span>${escape(labels[key])}${key==='bullensaga'?'<span class="bullen-header-external" aria-hidden="true">↗</span>':''}</span><small>${escape(descriptions[key])}</small></a>`).join('')}</div></details>`).join('');
 const contents=sections.length?`<div class="bullen-header-contents"><button type="button" class="bullen-header-control" id="bullen-contents-button" aria-expanded="false" aria-controls="bullen-contents-panel">ON THIS PAGE${chevron}</button><nav id="bullen-contents-panel" class="bullen-header-panel bullen-header-page-panel" aria-label="On this page" hidden><p class="bullen-header-eyebrow">${escape(label)} / contents</p>${sections.map(([id,text],i)=>`<a href="#${id}">${escape(text)}<span aria-hidden="true">${String(i+1).padStart(2,'0')}</span></a>`).join('')}</nav></div>`:'';
 return `<!-- BULLEN_SHELL_START: generated by qa/prerender-shells.mjs -->\n<header data-bullen-shell="" data-bullen-header="" data-bullen-shell-source="${hash}" class="bullen-site-shell${page==='index'?' bullen-home-shell':''}${['referrals','shares'].includes(page)?' is-admin':''}"><div class="bullen-header-inner"><a class="bullen-header-brand" href="/" aria-label="BULLENCIAGA home"${current('index')}>BULLENCIAGA<span>${escape(label)}</span></a><nav class="bullen-header-destinations" aria-label="Featured destinations">${featured.map(navLink).join('')}</nav><div class="bullen-header-controls">${contents}<button type="button" id="bullen-explore-button" class="bullen-header-control bullen-header-explore-control" aria-expanded="false" aria-controls="bullen-explore-panel"><span class="bullen-header-desktop-label">EXPLORE</span><span class="bullen-header-mobile-label">MENU</span><span class="bullen-header-hamburger" aria-hidden="true"><i></i><i></i></span></button></div><nav id="bullen-explore-panel" class="bullen-header-panel bullen-header-explore-panel" aria-label="Explore BULLENCIAGA" hidden><div class="bullen-header-panel-heading"><div><p class="bullen-header-eyebrow">BULLENCIAGA / directory</p><h2>More of the House.</h2></div><button class="bullen-header-close" type="button" aria-label="Close site menu">×</button></div><div class="bullen-header-directory">${groupsHtml}</div><div class="bullen-header-directory-footer"><div class="bullen-header-socials" aria-label="Community channels">${socials.map(extraLink).join('')}</div><details class="bullen-header-resources"><summary>Marketplaces &amp; data${chevron}</summary><div class="bullen-header-resource-links">${resources.map(extraLink).join('')}</div></details></div></nav></div></header>\n<!-- BULLEN_SHELL_END -->`;
};
const problems=[];let count=0;
for(const name of (await fs.readdir(site)).filter(n=>n.endsWith('.html')).sort()){
 const file=path.join(site,name);let source=await fs.readFile(file,'utf8');const before=source;
 const standalone=!source.includes('href="/bullen-ui.css"');
 if(standalone&&!source.includes('data-bullen-standalone')) source=source.replace('<html ',`<html data-bullen-standalone="${name.replace(/\.html$/,'')}" `);
 // The approved shared shell owns site navigation. Keep useful page controls
 // in a separate local toolbar; World identity is editorial content, untouched.
 if(!marker.test(source)){
  if(name==='platform.html') source=source.replace(/<header>([\s\S]*?)<\/header>/,(_,inside)=>`<div class="bullen-page-toolbar" data-page-toolbar="platform">${inside.replace(/<a class="brand"[\s\S]*?<\/a>/,'')}</div>`);
  if(name==='flywheel.html') source=source.replace(/<header>([\s\S]*?)<\/header>/,(_,inside)=>`<div class="bullen-page-toolbar" data-page-toolbar="flywheel">${inside.replace(/<a class="brand"[\s\S]*?<\/a>/,'').replace(/<nav aria-label="Page sections">[\s\S]*?<\/nav>/,'')}</div>`).replace("document.querySelectorAll('header nav a')","document.querySelectorAll('#bullen-contents-panel a')");
  if(name==='shares.html') source=source.replace(/<header>([\s\S]*?)<\/header>/,(_,inside)=>`<div class="bullen-page-toolbar" data-page-toolbar="shares">${inside.replace(/<a [\s\S]*?<\/a>/,'')}</div>`);
  if(name==='raiders.html') source=source.replace(/<header class="masthead">[\s\S]*?<\/header>/,'');
  if(name==='what-if-i-held.html') source=source.replace(/<header class="top">([\s\S]*?)<\/header>/,(_,inside)=>`<div class="bullen-page-toolbar" data-page-toolbar="holding">${inside.replace(/<a class="brand"[\s\S]*?<\/a>/,'')}</div>`);
 }
 if(!source.includes('href="/bullen-header.css"')) source=source.replace('</head>','<link rel="stylesheet" href="/bullen-header.css">\n</head>');
 // Bind the static header before deferred swap vendors or page applications.
 source=source.replace(/<script defer src="\/bullen-header\.js"><\/script>\n?/,'');
 source=source.replace(/<script\b/, '<script defer src="/bullen-header.js"></script>\n<script');
 if(name==='shares.html'&&!source.includes('src="/bullen-navigation.js"')) source=source.replace('</head>','<script defer src="/bullen-navigation.js"></script>\n</head>');
 const block=shell(name,source);
 source=marker.test(source)?source.replace(marker,()=>block):source.replace(/<body\b[^>]*>/,m=>`${m}\n${block}`);
 if(source!==before){if(check)problems.push(name);else await fs.writeFile(file,source);}
 count++;
}
if(problems.length)throw new Error(`Initial header differs from authority: ${problems.join(', ')}. Run node qa/prerender-shells.mjs.`);
console.log(`${check?'Checked':'Prerendered'} ${count} initial shared headers; Goods is served separately and untouched.`);
