// Refresh initial navigation after editing the builders in site/bullen-ui.js.
// Requires Playwright (or PLAYWRIGHT_MODULE pointing to its index.mjs).
// Optional CHROME_EXECUTABLE selects an installed Chrome. Run npm run manifest
// and update the homepage authority hash after reviewing the generated diff.
import fs from 'node:fs/promises';
import path from 'node:path';
import crypto from 'node:crypto';
import {createServer} from 'node:http';
const {chromium} = await import(process.env.PLAYWRIGHT_MODULE || 'playwright');
const site = path.resolve(import.meta.dirname, '../site');
const shellSource = (await fs.readFile(path.join(site, 'bullen-ui.js'), 'utf8')).split('  /* Warm same-origin page navigations')[0];
const shellHash = crypto.createHash('sha256').update(shellSource).digest('hex');
const marker = /<!-- BULLEN_SHELL_START[\s\S]*?<!-- BULLEN_SHELL_END -->/;
const sourceNeedle = "const shell = document.querySelector('header[data-bullen-shell]') || document.createElement('header');";
const types = {'.html':'text/html','.js':'text/javascript','.css':'text/css','.woff2':'font/woff2','.svg':'image/svg+xml'};
const server = createServer(async (req, res) => {
  const url = new URL(req.url, 'http://localhost');
  let name = url.pathname === '/' ? '/index.html' : url.pathname;
  if (!path.extname(name)) name += '.html';
  const file = path.resolve(site, '.' + name);
  if (!file.startsWith(site + path.sep)) return res.writeHead(403).end();
  try {
    let data = await fs.readFile(file);
    if (name === '/bullen-ui.js') {
      const js = data.toString();
      if (!js.includes(sourceNeedle)) throw new Error('Update the prerender builder hook');
      // Build fresh links from the canonical JS, rather than recapturing stale
      // static navigation. The homepage widget is moved into this fresh shell.
      data = js.replace(sourceNeedle, "const shell = document.createElement('header');");
    }
    res.writeHead(200, {'content-type': types[path.extname(file)] || 'application/octet-stream'}).end(data);
  } catch { res.writeHead(404).end(); }
});
await new Promise(resolve => server.listen(0, '127.0.0.1', resolve));
const origin = `http://127.0.0.1:${server.address().port}`;
const browser = await chromium.launch({headless:true, ...(process.env.CHROME_EXECUTABLE ? {executablePath:process.env.CHROME_EXECUTABLE} : {})});
try {
  const context = await browser.newContext({viewport:{width:440,height:850}});
  await context.route('**/*', route => new URL(route.request().url()).origin === origin ? route.continue() : route.abort());
  const page = await context.newPage();
  let count = 0;
  for (const name of await fs.readdir(site)) {
    if (!name.endsWith('.html')) continue;
    const file = path.join(site, name), source = await fs.readFile(file, 'utf8');
    if (!source.includes('href="/bullen-ui.css"')) continue;
    await page.goto(origin + '/' + name, {waitUntil:'domcontentloaded'});
    const shell = page.locator('header[data-bullen-hydrated="true"]').first();
    await shell.waitFor();
    const html = await shell.evaluate((el, hash) => { const copy = el.cloneNode(true); copy.removeAttribute('data-bullen-hydrated'); copy.setAttribute('data-bullen-shell-source', hash); return copy.outerHTML; }, shellHash);
    const block = '<!-- BULLEN_SHELL_START: generated by qa/prerender-shells.mjs -->\n' + html + '\n<!-- BULLEN_SHELL_END -->';
    if (!marker.test(source)) throw new Error(`${name} needs its initial shell markers`);
    await fs.writeFile(file, source.replace(marker, () => block));
    count++;
  }
  console.log(`Rendered ${count} initial headers; regenerate the manifest and verify the authority hash.`);
} finally { await browser.close(); server.close(); }
